services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    networks:
      - gym-network
    environment:
      JWT_SECRET: ${JWT_SECRET} 
  # workout-service:
  #   build:
  #     context: ./workout-service
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - gym-network

  # tracking-service:
  #   build:
  #     context: ./tracking-service
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - gym-network

  # nutrition-service:
  #   build:
  #     context: ./nutrition-service
  #   ports:
  #     - "3003:3003"
  #   networks:
  #     - gym-network

  # notification-service:
  #   build:
  #     context: ./notification-service
  #   ports:
  #     - "3004:3004"
  #   networks:
  #     - gym-network

  # api-gateway:
  #   build:
  #     context: ./api-gateway
  #   ports:
  #     - "80:80"
  #   networks:
  #     - gym-network

  postgres:
    image:  postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge

volumes:
  postgres-data:
