version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gym-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      retries: 5
      timeout: 5s

  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    networks:
      - gym-network
    environment:
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=10", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - gym-network
    depends_on:
      postgres:
        condition: service_healthy

  workout-service:
    build:
      context: ./workout-service
    ports:
      - "3001:3001"
    networks:
      - gym-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=10", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "80:80"
    networks:
      - gym-network
    depends_on:
      user-service:
        condition: service_healthy
      workout-service:
        condition: service_healthy
  
networks:
  gym-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
